# Generated by Django 3.0.1 on 2020-03-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20200303_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
