# Generated by Django 3.0.1 on 2020-03-04 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20200303_2022'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
