# Generated by Django 3.0.1 on 2020-03-04 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_delete_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='img4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='img5',
        ),
    ]
