# Generated by Django 3.0.1 on 2020-03-04 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
