# Generated by Django 3.0.1 on 2020-03-05 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_cartproducts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproducts',
            name='product',
        ),
        migrations.AddField(
            model_name='cartproducts',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cartproducts',
            name='product_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='cartproducts',
            name='username',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
