# Generated by Django 3.0.1 on 2020-03-05 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20200305_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproducts',
            name='price',
        ),
        migrations.RemoveField(
            model_name='cartproducts',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='cartproducts',
            name='username',
        ),
    ]
