# Generated by Django 3.0.1 on 2020-03-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_cartproducts_imagepath'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img2',
            field=models.ImageField(default='product.jpg', upload_to='product_pics'),
        ),
        migrations.AddField(
            model_name='product',
            name='img3',
            field=models.ImageField(default='product.jpg', upload_to='product_pics'),
        ),
        migrations.AddField(
            model_name='product',
            name='img4',
            field=models.ImageField(default='product.jpg', upload_to='product_pics'),
        ),
        migrations.AddField(
            model_name='product',
            name='img5',
            field=models.ImageField(default='product.jpg', upload_to='product_pics'),
        ),
        migrations.AddField(
            model_name='product',
            name='img6',
            field=models.ImageField(default='product.jpg', upload_to='product_pics'),
        ),
    ]
