# Generated by Django 3.0.1 on 2020-03-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_auto_20200307_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproducts',
            name='quantity',
            field=models.ImageField(default=1, upload_to=''),
        ),
    ]
