# Generated by Django 3.0.1 on 2020-03-14 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_cartproducts_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='img6',
        ),
        migrations.AlterField(
            model_name='cartproducts',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
