# Generated by Django 3.0.1 on 2020-03-16 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_auto_20200315_0207'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, max_length=150)),
                ('product_name', models.CharField(default=None, max_length=150)),
                ('price', models.FloatField(default=0.0)),
                ('imagePath', models.CharField(default=None, max_length=300)),
            ],
        ),
    ]
