# Generated by Django 3.0.1 on 2020-03-16 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='imagePath',
        ),
    ]
