# Generated by Django 3.0.1 on 2020-03-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_remove_wishlist_imagepath'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='imagePath',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
