# Generated by Django 3.0.2 on 2020-02-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='birthdate',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='users',
            name='contact_number',
            field=models.DecimalField(decimal_places=0, default=None, max_digits=10),
        ),
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='users',
            name='firstname',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='users',
            name='lastname',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
