# Generated by Django 3.0.1 on 2020-02-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200215_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='prfile_pics'),
        ),
    ]
