# Generated by Django 3.0.1 on 2020-02-20 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_users_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
