# Generated by Django 3.0.1 on 2020-02-26 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birthdate',
        ),
    ]
