# Generated by Django 3.0.1 on 2020-03-22 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20200322_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
