# Generated by Django 3.0.1 on 2020-03-22 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_orderdetails_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='imagepath',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
